CREATE DATABASE test1;
USE test1;
 CREATE TABLE users(
    id INT(250) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(250) NOT NULL,
    email VARCHAR (250) NOT NULL,
    phone VARCHAR(250) NOT NULL,
    bgroup VARCHAR(250) NOT NULL
 );

 CREATE  TABLE users1 (
   id INT(250) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    firstname VARCHAR(250) NOT NULL,
    lastname VARCHAR(250) NOT NULL,
    email VARCHAR (250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    gender VARCHAR(250) NOT NULL
 );

 CREATE TABLE users2 (
   id INT(250) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    email VARCHAR (250) NOT NULL
 );

 CREATE TABLE users3 (
   id INT(250) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL
 );

 CREATE DATABASE api;
 USE api;
  CREATE TABLE users(
   id INT(250) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    email VARCHAR (250) NOT NULL
 );
 